-- MySQL Script generated by MySQL Workbench
-- Mon Oct  5 12:56:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ExhibitionsServlet
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ExhibitionsServlet` ;

-- -----------------------------------------------------
-- Schema ExhibitionsServlet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ExhibitionsServlet` DEFAULT CHARACTER SET utf8 ;
USE `ExhibitionsServlet` ;

-- -----------------------------------------------------
-- Table `ExhibitionsServlet`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ExhibitionsServlet`.`user_role` ;

CREATE TABLE IF NOT EXISTS `ExhibitionsServlet`.`user_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `role_UNIQUE` (`role` ASC) VISIBLE)
ENGINE = InnoDB;
INSERT INTO user_role(role) VALUES ('ADMIN'), ('USER'), ('GUEST');


-- -----------------------------------------------------
-- Table `ExhibitionsServlet`.`usr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ExhibitionsServlet`.`usr` ;

CREATE TABLE IF NOT EXISTS `ExhibitionsServlet`.`usr` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `user_role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usr_user_role_idx` (`user_role_id` ASC) VISIBLE,
  CONSTRAINT `fk_usr_user_role`
    FOREIGN KEY (`user_role_id`)
    REFERENCES `ExhibitionsServlet`.`user_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
INSERT INTO usr(id, email, password, username, user_role_id) VALUES(1, 'superadmin@exhibitions.servlet', '1234', 'SuperAdmin', 1);


-- -----------------------------------------------------
-- Table `ExhibitionsServlet`.`exhibition_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ExhibitionsServlet`.`exhibition_status` ;

CREATE TABLE IF NOT EXISTS `ExhibitionsServlet`.`exhibition_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `status_name_UNIQUE` (`status_name` ASC) VISIBLE)
ENGINE = InnoDB;
INSERT INTO exhibition_status(status_name) VALUES ('ACTIVE'), ('EXPIRED'), ('CANCELED');


-- -----------------------------------------------------
-- Table `ExhibitionsServlet`.`exhibition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ExhibitionsServlet`.`exhibition` ;

CREATE TABLE IF NOT EXISTS `ExhibitionsServlet`.`exhibition` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ex_name` VARCHAR(45) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `open_time` VARCHAR(45) NOT NULL,
  `close_time` VARCHAR(45) NOT NULL,
  `description` VARCHAR(2000) NOT NULL,
  `price` INT NOT NULL,
  `themes` VARCHAR(200) NOT NULL,
  `exhibition_status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `exName_UNIQUE` (`ex_name` ASC) VISIBLE,
  INDEX `fk_exhibition_exhibition_status1_idx` (`exhibition_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_exhibition_exhibition_status1`
    FOREIGN KEY (`exhibition_status_id`)
    REFERENCES `ExhibitionsServlet`.`exhibition_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExhibitionsServlet`.`hall`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ExhibitionsServlet`.`hall` ;

CREATE TABLE IF NOT EXISTS `ExhibitionsServlet`.`hall` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hall_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `hall_name_UNIQUE` (`hall_name` ASC) VISIBLE)
ENGINE = InnoDB;
INSERT INTO hall(hall_name) VALUES ('SHEVCHENKO'), ('FRANKO'), ('KOSTENKO');


-- -----------------------------------------------------
-- Table `ExhibitionsServlet`.`exhibition_has_hall`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ExhibitionsServlet`.`exhibition_has_hall` ;

CREATE TABLE IF NOT EXISTS `ExhibitionsServlet`.`exhibition_has_hall` (
  `exhibition_id` INT NOT NULL,
  `hall_id` INT NOT NULL,
  PRIMARY KEY (`exhibition_id`, `hall_id`),
  INDEX `fk_exhibition_has_hall_hall1_idx` (`hall_id` ASC) VISIBLE,
  INDEX `fk_exhibition_has_hall_exhibition1_idx` (`exhibition_id` ASC) VISIBLE,
  CONSTRAINT `fk_exhibition_has_hall_exhibition1`
    FOREIGN KEY (`exhibition_id`)
    REFERENCES `ExhibitionsServlet`.`exhibition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exhibition_has_hall_hall1`
    FOREIGN KEY (`hall_id`)
    REFERENCES `ExhibitionsServlet`.`hall` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExhibitionsServlet`.`ticket_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ExhibitionsServlet`.`ticket_status` ;

CREATE TABLE IF NOT EXISTS `ExhibitionsServlet`.`ticket_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ticket_status_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ticket_status_name_UNIQUE` (`ticket_status_name` ASC) VISIBLE)
ENGINE = InnoDB;
INSERT INTO ticket_status(ticket_status_name) VALUES ('ACTIVE'), ('EXPIRED'), ('WAITING_REFUND'), ('REFUNDED');


-- -----------------------------------------------------
-- Table `ExhibitionsServlet`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ExhibitionsServlet`.`ticket` ;

CREATE TABLE IF NOT EXISTS `ExhibitionsServlet`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usr_id` INT NOT NULL,
  `exhibition_id` INT NOT NULL,
  `ticket_status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ticket_usr1_idx` (`usr_id` ASC) VISIBLE,
  INDEX `fk_ticket_exhibition1_idx` (`exhibition_id` ASC) VISIBLE,
  INDEX `fk_ticket_ticket_status1_idx` (`ticket_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_usr1`
    FOREIGN KEY (`usr_id`)
    REFERENCES `ExhibitionsServlet`.`usr` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_exhibition1`
    FOREIGN KEY (`exhibition_id`)
    REFERENCES `ExhibitionsServlet`.`exhibition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_ticket_status1`
    FOREIGN KEY (`ticket_status_id`)
    REFERENCES `ExhibitionsServlet`.`ticket_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
